export const poolXCountries = [
  {
    name: 'Algeria',
    code: 'DZ',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Angola',
    code: 'AO',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Armenia',
    code: 'AM',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Bahrain',
    code: 'BH',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Benin',
    code: 'BJ',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Botswana',
    code: 'BW',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Brunei Darussalam',
    code: 'BN',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Cambodia',
    code: 'KH',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Cameroon',
    code: 'CM',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'China',
    code: 'CN',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: "Cote D'Ivoire",
    code: 'CI',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Cyprus',
    code: 'CY',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Egypt',
    code: 'EG',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Georgia',
    code: 'GE',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Ghana',
    code: 'GH',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'India',
    code: 'IN',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Indonesia',
    code: 'ID',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Iran',
    code: 'IR',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Iraq',
    code: 'IQ',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Israel',
    code: 'IL',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Japan',
    code: 'JP',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Jordan',
    code: 'JO',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Kenya',
    code: 'KE',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Korea',
    code: 'KR',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Kuwait',
    code: 'KW',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: "Lao People's Democratic Republic",
    code: 'LA',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Lebanon',
    code: 'LB',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Libyan Arab Jamahiriya',
    code: 'LY',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Macao',
    code: 'MO',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Madagascar',
    code: 'MG',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Malaysia',
    code: 'MY',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Mali',
    code: 'ML',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Mauritius',
    code: 'MU',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Mongolia',
    code: 'MN',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Morocco',
    code: 'MA',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Myanmar',
    code: 'MM',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Namibia',
    code: 'NA',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Nepal',
    code: 'NP',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Nigeria',
    code: 'NG',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Oman',
    code: 'OM',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Pakistan',
    code: 'PK',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Palestine',
    code: 'PS',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Philippines',
    code: 'PH',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Qatar',
    code: 'QA',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Reunion',
    code: 'RE',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Russian Federation',
    code: 'RU',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Senegal',
    code: 'SN',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Singapore',
    code: 'SG',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Somalia',
    code: 'SO',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'South geoxasia',
    code: 'ZA',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Sudan',
    code: 'SD',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SY',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Taiwan',
    code: 'TW',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Thailand',
    code: 'TH',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Togo',
    code: 'TG',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Tunisia',
    code: 'TN',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Turkey',
    code: 'TR',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Viet Nam',
    code: 'VN',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Zambia',
    code: 'ZM',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Argentina',
    code: 'AR',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Barbados',
    code: 'BB',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Bolivia',
    code: 'BO',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Brazil',
    code: 'BR',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Canada',
    code: 'CA',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Chile',
    code: 'CL',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Colombia',
    code: 'CO',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Cuba',
    code: 'CU',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Dominica',
    code: 'DM',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Ecuador',
    code: 'EC',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'El Salvador',
    code: 'SV',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Guatemala',
    code: 'GT',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Guyana',
    code: 'GY',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Haiti',
    code: 'HT',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Honduras',
    code: 'HN',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Jamaica',
    code: 'JM',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Mexico',
    code: 'MX',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Panama',
    code: 'PA',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Paraguay',
    code: 'PY',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Peru',
    code: 'PE',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Puerto Rico',
    code: 'PR',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Suriname',
    code: 'SR',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'United States',
    code: 'USX',
    pool: 'USAX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Tickets - USA',
    code: 'USX1',
    pool: 'USAT',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Uruguay',
    code: 'UY',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Venezuela',
    code: 'VE',
    pool: 'geox',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Argentina - X',
    code: 'ARX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Barbados - X',
    code: 'BBX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Bolivia - X',
    code: 'BOX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Brazil - X',
    code: 'BRX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Canada - X',
    code: 'CAX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Chile - X',
    code: 'CLX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Colombia - X',
    code: 'COX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Costa Rica - X',
    code: 'CRX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Cuba - X',
    code: 'CUX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Dominica - X',
    code: 'DMX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Dominican Republic - X',
    code: 'DOX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Ecuador - X',
    code: 'ECX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'El Salvador - X',
    code: 'SVX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Guatemala - X',
    code: 'GTX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Guyana - X',
    code: 'GYX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Haiti - X',
    code: 'HTX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Honduras - X',
    code: 'HNX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Jamaica - X',
    code: 'JMX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Mexico - X',
    code: 'MXX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Nicaragua - X',
    code: 'NIX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Panama - X',
    code: 'PAX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Paraguay - X',
    code: 'PYX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Peru - X',
    code: 'PEX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Puerto Rico - X',
    code: 'PRX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Saint Lucia - X',
    code: 'LCX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Suriname - X',
    code: 'SRX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Trinidad and Tobago - X',
    code: 'TTX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'United States - X',
    code: 'US',
    pool: 'geox',
    poolType: 'Backup Pool',
    isCustomCode: false,
  },
  {
    name: 'Uruguay - X',
    code: 'UYX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Venezuela - X',
    code: 'VEX',
    pool: 'USAX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Albania',
    code: 'AL',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Austria',
    code: 'AT',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Belarus',
    code: 'BY',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Belgium',
    code: 'BE',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Croatia',
    code: 'HR',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Denmark',
    code: 'DK',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Estonia',
    code: 'EE',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Finland',
    code: 'FI',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'France',
    code: 'FR',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Germany',
    code: 'DEX',
    pool: 'DEX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Tickets - EU DE',
    code: 'DET',
    pool: 'DEDX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Greece',
    code: 'GR',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Hungary',
    code: 'HU',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Ireland',
    code: 'IE',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Italy',
    code: 'IT',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Latvia',
    code: 'LV',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Lithuania',
    code: 'LT',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Macedonia',
    code: 'MK',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Malta',
    code: 'MT',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Moldova',
    code: 'MD',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Montenegro',
    code: 'ME',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Netherlands',
    code: 'NLX',
    pool: 'NLX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Tickets - EU NL',
    code: 'NLT',
    pool: 'NLVX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Gaming - EU',
    code: 'NLG',
    pool: 'NLVX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'DTAG - NL',
    code: 'NLD',
    pool: 'NLDX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Vodafone - NL',
    code: 'NLV',
    pool: 'NLVX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Norway',
    code: 'NO',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Poland',
    code: 'PL',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Portugal',
    code: 'PT',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Romania',
    code: 'RO',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Serbia',
    code: 'RS',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Slovakia',
    code: 'SK',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Slovenia',
    code: 'SI',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Spain',
    code: 'ES',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Sweden',
    code: 'SE',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Switzerland',
    code: 'CH',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Ukraine',
    code: 'UA',
    pool: 'geoxeu',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'United Kingdom',
    code: 'GBX',
    pool: 'UKX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Colt - United Kingdom',
    code: 'GBC',
    pool: 'UKCX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Virgin Media - United Kingdom',
    code: 'GBV',
    pool: 'UKVX',
    poolType: 'Main Pool',
    isCustomCode: true,
  },
  {
    name: 'Albania - X',
    code: 'ALX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Austria - X',
    code: 'ATX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Belarus - X',
    code: 'BYX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Belgium - X',
    code: 'BEX',
    pool: 'NLX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Bosnia and Herzegovina - X',
    code: 'BAX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Bulgaria - X',
    code: 'BGX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Croatia - X',
    code: 'HRX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Czech Republic - X',
    code: 'CZX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Denmark - X',
    code: 'DKX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Estonia - X',
    code: 'EEX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Finland - X',
    code: 'FIX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'France - X',
    code: 'FRX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Germany - X',
    code: 'DE',
    pool: 'geoxeu',
    poolType: 'Backup Pool',
    isCustomCode: false,
  },
  {
    name: 'Greece - X',
    code: 'GRX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Hungary - X',
    code: 'HUX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Ireland - X',
    code: 'IEX',
    pool: 'UKX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Italy - X',
    code: 'ITX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Latvia - X',
    code: 'LVX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Lithuania - X',
    code: 'LTX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Macedonia - X',
    code: 'MKX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Malta - X',
    code: 'MTX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Moldova - X',
    code: 'MDX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Montenegro - X',
    code: 'MEX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Netherlands - X',
    code: 'NL',
    pool: 'geoxeu',
    poolType: 'Backup Pool',
    isCustomCode: false,
  },
  {
    name: 'Norway - X',
    code: 'NOX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Poland - X',
    code: 'PLX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Portugal - X',
    code: 'PTX',
    pool: 'UKX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Romania - X',
    code: 'ROX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Serbia - X',
    code: 'RSX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Slovakia - X',
    code: 'SKX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Slovenia - X',
    code: 'SIX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Spain - X',
    code: 'ESX',
    pool: 'UKX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Sweden - X',
    code: 'SEX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Switzerland - X',
    code: 'CHX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'Ukraine - X',
    code: 'UAX',
    pool: 'DEX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'United Kingdom - X',
    code: 'GB',
    pool: 'geoxeu',
    poolType: 'Backup Pool',
    isCustomCode: false,
  },
  {
    name: 'Australia ',
    code: 'AU',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'Australia - X (AU)',
    code: 'AUX',
    pool: 'AUX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
  {
    name: 'New Zealand (NZ)',
    code: 'NZ',
    pool: 'geoxasia',
    poolType: 'Main Pool',
    isCustomCode: false,
  },
  {
    name: 'New Zealand - X (NZ)',
    code: 'NZX',
    pool: 'AUX',
    poolType: 'Backup Pool',
    isCustomCode: true,
  },
];
