version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
  cloudrun: circleci/gcp-cloud-run@1.0.2
  jira: circleci/jira@1.3.1

jobs:
  build-test:
    docker:
      - image: cimg/node:18.20.2

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build
          command: npm run build

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test
          command: npm run test:verbose

workflows:
  build-test-publish:
    jobs:
      - build-test
